set WshShell = WScript.CreateObject("WScript.Shell")

WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10
WshShell.SendKeys "{TAB}"
WScript.Sleep 10

WshShell.SendKeys "{ENTER}"